// Verilog 导出
function exportVerilog() {
    if (components.length === 0) return alert("空电路无法导出");

    const inputComps = components.filter(c => (c.type === 'SWITCH' || c.type === 'CLOCK') && c.inputs.length === 0);
    const outputComps = components.filter(c => (c.type === 'LIGHT' || c.type === 'SEG7' || c.type === 'SEG8'));
    const sanitize = (name, id) => `sig_${name}_${id}`;
    const inputs = inputComps.map(c => ({ id: c.id, name: sanitize(c.type.toLowerCase(), c.id), width: 1 }));
    const outputs = outputComps.map(c => ({ id: c.id, name: sanitize(c.type.toLowerCase(), c.id), width: c.type === 'SEG7' ? 7 : (c.type === 'SEG8' ? 8 : 1) }));
    const internalComps = components.filter(c => !inputComps.includes(c) && !outputComps.includes(c) && c.type !== 'SCOPE');
    
    const allWires = new Set();
    const getWireName = (comp, isOutput, idx) => isOutput ? `${sanitize(comp.type, comp.id)}_out${idx}` : `${sanitize(comp.type, comp.id)}_in${idx}`;
    
    internalComps.forEach(comp => { for (let i = 0; i < comp.outputs.length; i++) allWires.add(getWireName(comp, true, i)); });
    inputComps.forEach(comp => { for (let i = 0; i < comp.outputs.length; i++) allWires.add(getWireName(comp, true, i)); });
    
    const wireConnections = new Map();
    wires.forEach(w => {
        const src = compMap.get(w.fromId), dst = compMap.get(w.toId); if (!src || !dst) return;
        const srcWire = getWireName(src, true, w.fromNodeIdx), dstWire = getWireName(dst, false, w.toNodeIdx);
        allWires.add(srcWire); allWires.add(dstWire); wireConnections.set(dstWire, srcWire);
    });
    
    let verilog = `// Generated by Turing Logic Simulator V7.5\nmodule top_design (\n`;
    const portList = inputs.map(inp => `  input wire ${inp.name}`).concat(outputs.map(out => `  output wire [${out.width-1}:0] ${out.name}`));
    verilog += portList.join(",\n") + (portList.length ? `\n` : ``) + `);\n\n  // Internal wires\n`;
    Array.from(allWires).forEach(w => verilog += `  wire ${w};\n`);
    
    let extraModules = "";

    verilog += `\n  // Component instantiations\n`;
    internalComps.forEach(comp => {
        const instName = `${sanitize(comp.type, comp.id)}_inst`;
        const getIn = (idx) => wireConnections.get(getWireName(comp, false, idx)) || "1'b0";
        const getOut = (idx) => getWireName(comp, true, idx);
        
        let portConnections = [], moduleName = "", paramStr = "";
        
        switch(comp.type) {
            case 'AND': case 'OR': case 'XOR': moduleName = comp.type.toLowerCase() + "_gate"; portConnections.push(`.in0(${getIn(0)}), .in1(${getIn(1)}), .out(${getOut(0)})`); break;
            case 'NOT': moduleName = "not_gate"; portConnections.push(`.in0(${getIn(0)}), .out(${getOut(0)})`); break;
            case 'AND_N': case 'OR_N': moduleName = comp.type.toLowerCase() + "_gate"; paramStr = ` #(.WIDTH(${comp.customN})) `;
                let inBuses = []; for(let i=comp.customN-1; i>=0; i--) inBuses.push(getIn(i)); portConnections.push(`.in({${inBuses.join(', ')}}), .out(${getOut(0)})`); break;
            case 'HA': moduleName = "half_adder"; portConnections.push(`.a(${getIn(0)}), .b(${getIn(1)}), .sum(${getOut(0)}), .carry(${getOut(1)})`); break;
            case 'FA': moduleName = "full_adder"; portConnections.push(`.a(${getIn(0)}), .b(${getIn(1)}), .cin(${getIn(2)}), .sum(${getOut(0)}), .cout(${getOut(1)})`); break;
            case 'MUX': moduleName = "mux2to1"; portConnections.push(`.in0(${getIn(0)}), .in1(${getIn(1)}), .sel(${getIn(2)}), .out(${getOut(0)})`); break;
            case 'MUX4': moduleName = "mux4to1"; portConnections.push(`.in({${getIn(3)}, ${getIn(2)}, ${getIn(1)}, ${getIn(0)}}), .sel({${getIn(5)}, ${getIn(4)}}), .out(${getOut(0)})`); break;
            case 'DFF': moduleName = "dff_with_rst"; portConnections.push(`.D(${getIn(0)}), .CLK(${getIn(1)}), .RST(${getIn(2)}), .Q(${getOut(0)})`); break;
            case 'JKFF': moduleName = "jkff_with_rst"; portConnections.push(`.J(${getIn(0)}), .CLK(${getIn(1)}), .K(${getIn(2)}), .RST(${getIn(3)}), .Q(${getOut(0)}), .QN(${getOut(1)})`); break;
            case 'TFF': moduleName = "tff_with_rst"; portConnections.push(`.T(${getIn(0)}), .CLK(${getIn(1)}), .RST(${getIn(2)}), .Q(${getOut(0)}), .QN(${getOut(1)})`); break;
            case 'CNT4': moduleName = "counter_4bit"; portConnections.push(`.EN(${getIn(0)}), .CLK(${getIn(1)}), .RST(${getIn(2)}), .Q({${getOut(3)}, ${getOut(2)}, ${getOut(1)}, ${getOut(0)}}), .COUT(${getOut(4)})`); break;
            case 'DEC24': moduleName = "decoder_2to4"; portConnections.push(`.in({${getIn(1)}, ${getIn(0)}}), .out({${getOut(3)}, ${getOut(2)}, ${getOut(1)}, ${getOut(0)}})`); break;
            case 'DEC38': moduleName = "decoder_3to8"; portConnections.push(`.in({${getIn(2)}, ${getIn(1)}, ${getIn(0)}}), .out({${getOut(7)}, ${getOut(6)}, ${getOut(5)}, ${getOut(4)}, ${getOut(3)}, ${getOut(2)}, ${getOut(1)}, ${getOut(0)}})`); break;
            case 'ENC42': moduleName = "encoder_4to2_priority"; portConnections.push(`.in({${getIn(3)}, ${getIn(2)}, ${getIn(1)}, ${getIn(0)}}), .valid(${getOut(0)}), .code({${getOut(2)}, ${getOut(1)}})`); break;
            case 'REGBANK': moduleName = "regbank_16x16"; let outBuses = []; for(let i=15; i>=0; i--) outBuses.push(getOut(i));
                portConnections.push(`.addr({${getIn(3)}, ${getIn(2)}, ${getIn(1)}, ${getIn(0)}}), .data_in(16'b0), .we(1'b0), .clk(1'b0), .data_out({${outBuses.join(', ')}})`); break;
            case 'ROM16': 
                moduleName = `rom_16x16_${comp.id}`; 
                let rBuses = []; for(let i=15; i>=0; i--) rBuses.push(getOut(i));
                portConnections.push(`.addr({${getIn(3)}, ${getIn(2)}, ${getIn(1)}, ${getIn(0)}}), .data_out({${rBuses.join(', ')}})`); 
                // 特化 ROM 模块生成
                extraModules += `module ${moduleName} (input [3:0] addr, output reg [15:0] data_out);\n  always @(*) begin\n    case(addr)\n`;
                for(let i=0; i<16; i++) extraModules += `      4'd${i}: data_out = 16'h${comp.state[i].toString(16).padStart(4, '0')};\n`;
                extraModules += `      default: data_out = 16'h0000;\n    endcase\n  end\nendmodule\n\n`;
                break;
        }
        verilog += `  ${moduleName} ${paramStr}${instName} (\n    ${portConnections.join(',\n    ')}\n  );\n\n`;
    });
    
    verilog += `  // Connect top-level ports\n`;
    inputComps.forEach(comp => verilog += `  assign ${sanitize(comp.type, comp.id)}_out0 = ${sanitize(comp.type.toLowerCase(), comp.id)};\n`);
    outputComps.forEach(comp => {
        const portName = sanitize(comp.type.toLowerCase(), comp.id);
        if (comp.type === 'LIGHT') verilog += `  assign ${portName} = ${wireConnections.get(getWireName(comp, false, 0)) || "1'b0"};\n`;
        else {
            const bits = []; for (let i = 0; i < (comp.type === 'SEG7' ? 7 : 8); i++) bits.push(wireConnections.get(getWireName(comp, false, i)) || "1'b0");
            verilog += `  assign ${portName} = {${bits.reverse().join(", ")}};\n`;
        }
    });
    
    verilog += `\nendmodule\n`;
    
    verilog += `\n// ========== ROM Instances ==========\n${extraModules}`;

    verilog += `\n// ========== Primitive modules ==========\n`;
    verilog += `module and_gate (input in0, in1, output out);\n  assign out = in0 & in1;\nendmodule\n\n`;
    verilog += `module or_gate (input in0, in1, output out);\n  assign out = in0 | in1;\nendmodule\n\n`;
    verilog += `module not_gate (input in0, output out);\n  assign out = ~in0;\nendmodule\n\n`;
    verilog += `module xor_gate (input in0, in1, output out);\n  assign out = in0 ^ in1;\nendmodule\n\n`;
    verilog += `module and_n_gate #(parameter WIDTH=4) (input [WIDTH-1:0] in, output out);\n  assign out = &in;\nendmodule\n\n`;
    verilog += `module or_n_gate #(parameter WIDTH=4) (input [WIDTH-1:0] in, output out);\n  assign out = |in;\nendmodule\n\n`;
    verilog += `module half_adder (input a, b, output sum, carry);\n  assign sum = a ^ b;\n  assign carry = a & b;\nendmodule\n\n`;
    verilog += `module full_adder (input a, b, cin, output sum, cout);\n  wire s1, c1, c2;\n  assign s1 = a ^ b;\n  assign sum = s1 ^ cin;\n  assign c1 = a & b;\n  assign c2 = s1 & cin;\n  assign cout = c1 | c2;\nendmodule\n\n`;
    verilog += `module mux2to1 (input in0, in1, sel, output out);\n  assign out = sel ? in1 : in0;\nendmodule\n\n`;
    verilog += `module mux4to1 (input [3:0] in, input [1:0] sel, output out);\n  assign out = in[sel];\nendmodule\n\n`;
    verilog += `module dff_with_rst (input D, CLK, RST, output Q);\n  reg q_reg;\n  always @(posedge CLK or posedge RST) begin\n    if (RST) q_reg <= 1'b0;\n    else q_reg <= D;\n  end\n  assign Q = q_reg;\nendmodule\n\n`;
    verilog += `module jkff_with_rst (input J, CLK, K, RST, output Q, QN);\n  reg q_reg;\n  always @(posedge CLK or posedge RST) begin\n    if (RST) q_reg <= 1'b0;\n    else case ({J, K})\n      2'b01: q_reg <= 1'b0;\n      2'b10: q_reg <= 1'b1;\n      2'b11: q_reg <= ~q_reg;\n      default: q_reg <= q_reg;\n    endcase\n  end\n  assign Q = q_reg;\n  assign QN = ~q_reg;\nendmodule\n\n`;
    verilog += `module tff_with_rst (input T, CLK, RST, output Q, QN);\n  reg q_reg;\n  always @(posedge CLK or posedge RST) begin\n    if (RST) q_reg <= 1'b0;\n    else if (T) q_reg <= ~q_reg;\n  end\n  assign Q = q_reg;\n  assign QN = ~q_reg;\nendmodule\n\n`;
    verilog += `module counter_4bit (input EN, CLK, RST, output [3:0] Q, output COUT);\n  reg [3:0] count;\n  always @(posedge CLK or posedge RST) begin\n    if (RST) count <= 4'b0;\n    else if (EN) count <= count + 1;\n  end\n  assign Q = count;\n  assign COUT = (count == 4'd15 && EN);\nendmodule\n\n`;
    verilog += `module decoder_2to4 (input [1:0] in, output [3:0] out);\n  assign out = 1 << in;\nendmodule\n\n`;
    verilog += `module decoder_3to8 (input [2:0] in, output [7:0] out);\n  assign out = 1 << in;\nendmodule\n\n`;
    verilog += `module encoder_4to2_priority (input [3:0] in, output valid, output [1:0] code);\n  assign {valid, code} = (in[3]) ? {2'b11, 2'b11} :\n                         (in[2]) ? {2'b11, 2'b10} :\n                         (in[1]) ? {2'b11, 2'b01} :\n                         (in[0]) ? {2'b11, 2'b00} :\n                         {2'b00, 2'b00};\nendmodule\n\n`;
    verilog += `module regbank_16x16 (input [3:0] addr, input [15:0] data_in, input we, clk, output [15:0] data_out);\n  reg [15:0] regs [0:15];\n  always @(posedge clk) if (we) regs[addr] <= data_in;\n  assign data_out = regs[addr];\nendmodule\n`;
    
    const blob = new Blob([verilog], { type: 'text/plain' });
    const a = document.createElement('a'); a.href = URL.createObjectURL(blob); a.download = 'top_design.v';
    document.body.appendChild(a); a.click(); document.body.removeChild(a); URL.revokeObjectURL(a.href);
}

rebuildSimIndex(); loop();